// <auto-generated />
using System;
using HaushaltsbuchWPF.Class;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HaushaltsbuchWPF.Migrations
{
    [DbContext(typeof(HBContext))]
    [Migration("20220208091145_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HaushaltsbuchWPF.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BookingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KontoId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StandingOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("KontoId");

                    b.HasIndex("StandingOrderId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("HaushaltsbuchWPF.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KontoNameId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("HaushaltsbuchWPF.Konto", b =>
                {
                    b.Property<int>("KontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("KontoAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KontoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KontoId");

                    b.ToTable("Konto");
                });

            modelBuilder.Entity("HaushaltsbuchWPF.StandingOrder", b =>
                {
                    b.Property<int>("StandingOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("KontoId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OderName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Repetition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StandingOrderDateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StandingOrderDateStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("StandingOrderId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("KontoId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("StandingOrder");
                });

            modelBuilder.Entity("HaushaltsbuchWPF.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategory");
                });

            modelBuilder.Entity("HaushaltsbuchWPF.Booking", b =>
                {
                    b.HasOne("HaushaltsbuchWPF.Category", "Category")
                        .WithMany("Booking")
                        .HasForeignKey("CategoryId");

                    b.HasOne("HaushaltsbuchWPF.Konto", "Konto")
                        .WithMany("Booking")
                        .HasForeignKey("KontoId");

                    b.HasOne("HaushaltsbuchWPF.StandingOrder", "StandingOrder")
                        .WithMany()
                        .HasForeignKey("StandingOrderId");

                    b.HasOne("HaushaltsbuchWPF.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId");

                    b.Navigation("Category");

                    b.Navigation("Konto");

                    b.Navigation("StandingOrder");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("HaushaltsbuchWPF.StandingOrder", b =>
                {
                    b.HasOne("HaushaltsbuchWPF.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("HaushaltsbuchWPF.Konto", "Konto")
                        .WithMany()
                        .HasForeignKey("KontoId");

                    b.HasOne("HaushaltsbuchWPF.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId");

                    b.Navigation("Category");

                    b.Navigation("Konto");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("HaushaltsbuchWPF.SubCategory", b =>
                {
                    b.HasOne("HaushaltsbuchWPF.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HaushaltsbuchWPF.Category", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("HaushaltsbuchWPF.Konto", b =>
                {
                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
